name: Build Site

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --quiet --upgrade pip
        if [ -f tools/requirements.txt ]; then pip install --quiet -r tools/requirements.txt; fi
      
    - name: Build site
      run: |
        python tools/build_manager.py --full > /dev/null 2>&1
        
    - name: Generate assets
      run: |
        python tools/generate_assets.py > /dev/null 2>&1
        
    - name: Build feeds
      run: |
        python tools/build_feeds.py > /dev/null 2>&1
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages
        force_orphan: true
        enable_jekyll: false
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'chore: deploy site [skip ci]'
