name: Lint

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --quiet --upgrade pip
        pip install --quiet flake8 black isort
        if [ -f tools/requirements.txt ]; then pip install --quiet -r tools/requirements.txt; fi
      
    - name: Check formatting with black
      run: |
        black --quiet --check tools/
        
    - name: Check imports with isort
      run: |
        isort --quiet --check-only tools/
        
    - name: Lint with flake8
      run: |
        flake8 --quiet tools/
