name: Validate Content

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]
    paths:
      - 'notes/**'
      - 'images/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --quiet --upgrade pip
        if [ -f tools/requirements.txt ]; then pip install --quiet -r tools/requirements.txt; fi
      
    - name: Validate notes
      run: |
        python tools/validate_notes.py > /dev/null 2>&1
        
    - name: Validate images
      run: |
        python tools/validate_images.py > /dev/null 2>&1
